### ISSUE TITLE
Clean Gridsome install + this plugin = fails

### ISSUE THREAD

**Issue by studio-sixtyeight** [indiepaul/gridsome-plugin-uikit#2]
Hello,

I just started a new gridsome project via: gridsome create my-gridsome-site 
— all works fine.
Next I install this plugin and get 82 vulnerabilities (1 low, 43 moderate, 27 high, 11 critical)

Not sure what is going on.

**Comment by indiepaul** [comment]
Hello, thanks for this. I haven't updated this plugin in the longest time, so the dependencies are quite outdated, hence the vulnerabilities. 
I'll update it asap and let you know.

**Comment by indiepaul** [comment]
I've done some digging and I can't seem to exactly reproduce your issue. 
I've created a new project as well and got this:
`42 vulnerabilities (13 moderate, 26 high, 3 critical)`

Installing the plugin isn't changing this number, and the project is working fine even with the vulnerabilities.
So, I believe they are coming from some other source. 
The plugin only has one dependency i.e. `uikit`, which itself has no dependencies, and the latest version is being downloaded. 

Can you provide any additional information, perhaps I can identify you find the source of the crash?
Any other logs?
What's in your gridsome.config.js?

**Comment by nitras** [comment]
Hello there. Thanks for your anser.
When I create a new project in gridsome and add your plugin I can boot up indeed.

However. The moment other packages are added it goes wrong. 
`
MYPROJECT/node_modules/gridsome-plugin-uikit/gridsome.client.js:1
import 'uikit/dist/css/uikit.min.css'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/MYPROJECT/node_modules/gridsome/lib/utils/Plugins.js:16:27
    at Array.map (<anonymous>)
    at new Plugins (/Users/MYPROJECT/node_modules/gridsome/lib/utils/Plugins.js:14:43)
    at Service.init (/Users/MYPROJECT/node_modules/gridsome/lib/Service.js:60:20)
    at Service.bootstrap (/Users/MYPROJECT/node_modules/gridsome/lib/Service.js:40:23)
    at module.exports (/Users/MYPROJECT/node_modules/gridsome/lib/commands/develop.js:15:54)
    at /Users/MYPROJECT/node_modules/gridsome/index.js:33:12
    at Command.<anonymous> (/Users/MYPROJECT/node_modules/gridsome/index.js:11:27)
    `
    This is in my gridsome.config.js
    
    `module.exports = {
	siteName: 'Gridsome',
	plugins: [
		{
			use: 'gridsome-plugin-uikit',
		},
	],
};
`

And this is my package.json (this is based on the project that crashed. Meaning: if I delete all packages except gridsome and uikit the project works. But I am too new to all this to understand what goes wrong.

`
{
	"name": "ABCFLEXI-2023",
	"private": true,
	"scripts": {
		"develop": "gridsome develop",
		"explore": "gridsome explore",
		"build": "gridsome build"
	},
	"dependencies": {
		"@gridsome/transformer-json": "^0.2.1",
		"gridsome": "^0.0.4",
		"gridsome-plugin-uikit": "^1.0.0",
		"intersection-observer": "^0.12.0",
		"nprogress": "^0.2.0"
	},
	"devDependencies": {
		"node-sass": "^8.0.0",
		"sass-loader": "^10.1.1",
		"style-resources-loader": "^1.4.1",
		"vue-svg-loader": "^0.16.0"
	}
}

`

your insights are appreciated!
Thank you.

**Comment by studio-sixtyeight** [comment]
Hello Thanks for your answer.

I was able to restore my project.
I had to delete the devDependencies and install them again manually... For some reason now these sit in the Depencenies array and the project works fine.

So I deleted these from my package.json
`"devDependencies": {
		"node-sass": "^5.0.0",
		"sass-loader": "^10.1.1",
		"style-resources-loader": "^1.4.1",
		"vue-svg-loader": "^0.16.0"
	}`
	
	Installed them again via npm I <PACKAGENAME>
	
	and now it looks like this
	
	`
	"dependencies": {
		"@gridsome/source-filesystem": "^0.6.2",
		"@gridsome/transformer-json": "^0.2.1",
		"@gridsome/transformer-remark": "^0.6.4",
		"gridsome": "^0.7.0",
		"gridsome-plugin-uikit": "^1.0.0",
		"intersection-observer": "^0.12.0",
		"node-sass": "^8.0.0",
		"nprogress": "^0.2.0",
		"sass-loader": "^13.2.0",
		"style-resources-loader": "^1.5.0",
		"vue-svg-loader": "^0.16.0"
	}
	`
	
	
	I am baffled why, I am unsure what is going on. But thank you for your time.

**Comment by indiepaul** [comment]
Oh, Alright. Great to hear you got it working.
